### PR TITLE
[+] Swedish (file:`dict_sv.po`)

### PR DESCRIPTION
**Pull request by loneicewolf**
# Hi!
First things first, I love DiE, as well as other tools you have developed, and many more the community has helped with! Without these (__*marvelous*__) tools, It would be very difficult to "begin" anything related to malware and non-malware related analyses. **Thank you!**

## What this PR is
- [x] I added Swedish translation! I tried to be consistent, and take as many 'scenarios' into context, so each translation would be fitting for different cases, I hope it all is well typed; if something is off, point it out!

## Related Issues
- [x] I [asked first](https://github.com/horsicq/XTranslation/issues/134) before making this PR to be sure it was "good to go" 

## Notes
I see some is not 100% (like other languages, not this one)  some is 90% or 99%, I **think**, this is 100% Swedish, I don't find any empty "" when searching, and I looked 3 or probably 5 times to be sure, and 2 times proofread; but if anything is problematic or if someone is unsure, I can try to explain a line, just point out the line and ill do my best!

## Additional Notes
- Do not rush! No pressure/stress
- Take your time, it's all good

## Final words/Conclusion
Thanks! I always wanted to show how much I appreciate both you, the contributors and of course - *the tools*. Have a amazing week, you all do a (positive) difference by just existing! 

Over n out!

Will.

### CODE REVIEW

**Comment by loneicewolf** [comment]
Also, sorry I didn't change the list of 'completed languages', I only added the language file, should I have done that too? I am sorry if I misunderstood!

**Comment by horsicq** [comment]
Thanks a lot!

**Comment by horsicq** [comment]
> Also, sorry I didn't change the list of 'completed languages', I only added the language file, should I have done that too? I am sorry if I misunderstood!

We will fix it. Do not worry!

**Comment by loneicewolf** [comment]
Oh! That was quick, and it's me who gonna say thanks, 
have a lovely week! and take care;

warm, warm wishes from Sweden!
❤️

**Comment by greenozon** [comment]
shouldn't line 7
```
"X-Language: en_US\n"
```

denote Swedish language?

**Comment by loneicewolf** [comment]
> shouldn't line 7
> 
> ```
> "X-Language: en_US\n"
> ```
> 
> denote Swedish language?

OH! I didn't know I should have changed that too, should I change it and make another - PR? thanks for pointing out, i was so focused on the whole list, I thought that was metadata, my bad! I had no clue `:o`

**Comment by jimdi** [comment]
https://github.com/greenozon thx! fixed

**Pull request merged**
