### PR TITLE
correct some mistakes

### PR DESCRIPTION
**Pull request by ShiaoQuR**

### CODE REVIEW

**Comment by ShiaoQuR** [comment]
Is it possible to point out which file(s) these strings came from? It's somehow hard to translate without the actual context...

**Comment by horsicq** [comment]
Thanks a lot for the translation!

**Comment by horsicq** [comment]
I will try to research the translation format and make context if it is possible.

**Comment by ShiaoQuR** [comment]
It seems that .ts(Qt Linguist) files from DIE-engine/gui_source/translation need a complete update. These translations are not working correctly.



That string "Base address" doesn't appear in current [.ts file](https://github.com/horsicq/DIE-engine/blob/master/gui_source/translation/die_zh.ts) either. I compiled the latest version on my laptop and found this file modified but untranslated, I'm not sure if it is not imported back correctly...

**Comment by horsicq** [comment]
Thanks a lot for the report. I updated all ts files for Detect It Easy: https://github.com/horsicq/DIE-engine/commit/515117bbec55a5f73b64f51ba6f54c4820acbac2

Could you please try again.

**Comment by ShiaoQuR** [comment]
It looks perfect now after a recompilation. Thanks for your work!

**Pull request merged**
