### PR TITLE
Fix: 2022-07-13

### PR DESCRIPTION
**Pull request by keowu**
Hello Hors,
New translations on the way, at some point maybe we will have many strings to translate, it would be nice if we had some examples of where they would be applied within each application I believe that this way we could improve communication and translation even more, anyway great job!

Thx,
Keowu

### CODE REVIEW

**Comment by horsicq** [comment]
Thanks a lot! I let you know if I will make a build with all new translations.

**Comment by horsicq** [comment]
https://github.com/horsicq/Detect-It-Easy/releases/tag/Beta

**Comment by horsicq** [comment]
If some words are not yet translated. It will all be updated after a while at the same link. https://github.com/horsicq/Detect-It-Easy/releases/tag/Beta

**Comment by keowu** [comment]
cool, i'll check

Thx,
Keowu

-------- Mensagem Original --------
Em 14 de jul. de 2022 04:51, Hors escreveu:

**Pull request merged**
