### PR TITLE
Update Swedish Translations: Fix Typos and Capitalization Issues + 1 German word

### PR DESCRIPTION
**Pull request by loneicewolf**
Hi,
- First of all I have made some errors in the Swedish file,  **I deeply apologize for this.** 
- Second, I have added one German word `Crypter:Verschlüsseler`

## The issues
I have fixed several issues in the Swedish translations, including:
- [x] Typos
- [x] Capitalization errors (both uppercase and lowercase inconsistencies)
- [x] Incomplete phrases due to navigation issues in the file

I'm sorry;

Best regards,
Loneicewolf.

### CODE REVIEW

**Comment by loneicewolf** [comment]
This is the major of the fix, I think this was all

**Comment by loneicewolf** [comment]
this is hopefully the last PR/issue I will make, I have proofread and I can't find anything else, I apologize once more for inconvenience.

**Comment by horsicq** [comment]
Great! Thank you! :)

**Comment by loneicewolf** [comment]
Thank you so much for being so understanding! ❤️  Good luck with everything you are up to! **Amazing Super/Effort** you put in into your research/work! :)

**Pull request merged**
